version: '3.9'
networks:
  obref:
services:
  postgres_db:
    container_name: postgres_db
    image: postgres:11
    ports:
      - "8082:5432"
    hostname:   postgres_db
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=split_eazy