ALTER TABLE users
ADD COLUMN email_address VARCHAR(255) UNIQUE NOT NULL,
ADD COLUMN password TEXT NOT NULL,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_name ON users(name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email_address);